In [18]:
import tensorflow as tf
import tensorflow.keras as tfk
import tensorflow.keras.layers as tfkl
from tensorflow.keras.models import Sequential


from google.colab import drive
import numpy as np
import pandas as pd

In this example, we're going to train a [CharRNN](http://karpathy.github.io/2015/05/21/rnn-effectiveness/) on a body of Shakespearian text. Ultimtely, this is an unsuperived learning task. But similar to our previous explorations in unsupervised DL, we will use an unlabeled dataset and create many samples of labeled data that we can use with our familiar supervised loss functions. The result will be a model that has learned the statistical properties of the input text, and can then be considered a "generative" model of language because we can use it to generate synthetic passages of Shakespeare.  

In [19]:
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/


In [20]:
file_path = "/content/gdrive/MyDrive/shakespeare.txt"

with open(file_path,"r") as f:
  text = f.read()

We've loaded our Shakespeare text, let's take a look at a random snippet.

In [21]:
print(text[31600:32000])

 lies i' the second chamber?
  LADY MACBETH. Donalbain.
  MACBETH. This is a sorry sight.           [Looks on his hands.
  LADY MACBETH. A foolish thought, to say a sorry sight.
  MACBETH. There's one did laugh in 's sleep, and one cried,
      "Murther!"
    That they did wake each other. I stood and heard them,
    But they did say their prayers and address'd them
    Again to sleep.
  LADY MACB


We need to convert our text into numeric arrays, the next several blocks accomplish this.

First, we'll create a mapping between characters and their numeric index. We'll also create the reverse mapping, which is useful.

In [22]:
chars = sorted(list(set(text)))
print('total chars:', len(chars))
char_indices = dict((c, i) for i, c in enumerate(chars))
indices_char = dict((i, c) for i, c in enumerate(chars))

total chars: 75


Next, we'll create a training set of sub-sequences. Remember, we're trying to train a model to be able to predict the next chracter if it is given several characters of a subsequence. So we will create training pairs where each X is a fixed-length subsequences and each Y is the corresponding next letter in the text.

In [23]:
maxlen = 40
step = 3
sub_sequences = []
next_chars = []
for i in range(0, len(text) - maxlen, step):
    sub_sequences.append(text[i: i + maxlen])
    next_chars.append(text[i + maxlen])
print('nb sequences:', len(sub_sequences))

nb sequences: 38700


In [24]:
k=300
print("(Sequence):\n" + sub_sequences[k])
print("\n(Target Character): \n" + next_chars[k])

(Sequence):
 and other Apparitions
  Lords, Gentleme

(Target Character): 
n


Next we'll create one-hot vectors for our sub-sequences. The tensor we create here will be shaped as (num_sequences x sequence_length x alphabet_size).

In [25]:
X = np.zeros((len(sub_sequences), maxlen, len(chars)), dtype=np.uint8 )
Y = np.zeros((len(sub_sequences), len(chars)), dtype=np.uint8)
for i, seq in enumerate(sub_sequences):
    for t, char in enumerate(seq):
        X[i, t, char_indices[char]] = 1
        Y[i, char_indices[next_chars[i]]] = 1

In [26]:
X[0,0,:]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=uint8)

In [27]:
Y[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

Our RNN model will be quite simple.

In [28]:
char_rnn = Sequential()
char_rnn.add(tfkl.LSTM(128, input_shape=(maxlen, len(chars))))
char_rnn.add(tfkl.Dense(len(chars),activation="softmax"))

In [29]:
char_rnn.compile(loss='categorical_crossentropy', optimizer=tfk.optimizers.RMSprop(lr=0.01))

In [43]:
char_rnn.fit(X,Y, epochs=20, batch_size=1024)

Epoch 1/20
38/38 [==============================] - 1s 18ms/step - loss: 0.4029
Epoch 2/20
38/38 [==============================] - 1s 16ms/step - loss: 0.3979
Epoch 3/20
38/38 [==============================] - 1s 16ms/step - loss: 0.3916
Epoch 4/20
38/38 [==============================] - 1s 17ms/step - loss: 0.3906
Epoch 5/20
38/38 [==============================] - 1s 16ms/step - loss: 0.3865
Epoch 6/20
38/38 [==============================] - 1s 16ms/step - loss: 0.3802
Epoch 7/20
38/38 [==============================] - 1s 16ms/step - loss: 0.3787
Epoch 8/20
38/38 [==============================] - 1s 16ms/step - loss: 0.3759
Epoch 9/20
38/38 [==============================] - 1s 16ms/step - loss: 0.3717
Epoch 10/20
38/38 [==============================] - 1s 17ms/step - loss: 0.3661
Epoch 11/20
38/38 [==============================] - 1s 17ms/step - loss: 0.3607
Epoch 12/20
38/38 [==============================] - 1s 16ms/step - loss: 0.3627
Epoch 13/20
38/38 [==================

Once we have a trained model, we can simulate new text by making predictions about the next character and then drawing characters in proportion to the predicted probabilities. And then simple repeat that process over and over, each time drawing the next character.

In [44]:
def draw_char(probs):
    probs = np.asarray(probs).astype('float64')
    if sum(probs) != 1.0:
      probs = probs / np.sum(probs)
    draw = np.random.choice(range(len(probs)) , p=probs)
    return draw

def sample_text(model, sample_length=100):
    start = np.random.randint(0, len(text) - maxlen - 1)
    sequence = text[start: start + maxlen]
  
    x_preds = np.zeros((sample_length, maxlen, len(chars)))
    for i in range(sample_length):
        for t, char in enumerate(sequence[-maxlen:]):
            x_preds[i, t, char_indices[char]] = 1.

        preds = model.predict(np.expand_dims(x_preds[i,:,:], axis=0), verbose=0)[0]
        next_index = draw_char(preds)
        next_char = indices_char[next_index]

        sequence += next_char
    return sequence

In [47]:
sim = sample_text(char_rnn,sample_length=500)

In [48]:
print(sim)

in their stead,
    Curses, not loud but deather sir, them to gee
    And ithim dors and sleesitiess; Thane of may
be hangs.
  DOC. [laspont, you, greas porfannelv?
Cort, thring of them
    Say, is time to ataple!
    Give my elverving int had been?
  LADY MACBETH. O truth and gid o' tiends within.
  FIRST WITCH. A bould their fell tongusine.
  MACBETH. Fake of Game?
  ROSS. Bean Banquo offelt Macbeth streand somory.
  GECTHERER. Whate you noble puts and nature in eas;
    The graceds theme his day, would the otce stelt,
    With on t


Notice that we can do pretty well to learn the typical statistical patterns of this text and then simulate new text that appears to be very similar to legitimate Shakespeare. 

But just a caution - we can also do pretty well with a much simpler method (Markov model): http://nbviewer.jupyter.org/gist/yoavg/d76121dfde2618422139

So the lesson is to try something simple before jumping right in to deep learning.

## Exercise

In this example, we're going to use an RNN for sequence classification. The task we'll set up is to generate a training set of randomized strings, and train our model to detect whether a string contains any vowels.

First, we'll create a training dataset of short randomized character sequences and the corresponding label of whether or not they contain at least one vowel.

In [84]:
import string

In [85]:
def contains_vowels(sequence):
  vowels = ["a", "e", "i", "o", "u"]
  return any([vowel in list(sequence) for vowel in vowels])

In [86]:
contains_vowels("gradient")

True

In [87]:
sequences = []
labels = []
for i in range(1000):
 char_list = np.random.choice( list(string.ascii_lowercase), size = 5, replace=True)
 seq = "".join(char_list)
 sequences.append(seq)
 labels.append(int(contains_vowels(seq)))

In [88]:
df = pd.DataFrame({"sequence": sequences, "label":labels})

In [89]:
df.head()

sequence  label
0    zmjlx      0
1    ydvzc      0
2    jsrxp      0
3    gltho      1
4    qisul      1

Next, set up and train an RNN (of any type) to solve this task. What preprocessing will you need to do first on the raw data in order to prepare it for the network?

In [90]:
# Data Preprocessing
## Going to get a list of the unique characters used
import itertools
# Define empty list that will contain list of letters in each string
encoded = []
# For each of the 1000 strings...
for i in range(len(sequences)):
  # List the letters in this string
  string = list(sequences[i])
  # Append the letters of this string as a small list to the list of lists
  encoded.append(string)
# List all letters in all strings as single list of letters
long_list = list(itertools.chain.from_iterable(encoded))
# Define encoding (1-26)
chars = sorted(list(set(long_list)))
print('total chars:', len(chars))

# Create encoding and reverse encoding
char_indices = dict((c, i) for i, c in enumerate(chars))
indices_char = dict((i, c) for i, c in enumerate(chars))

total chars: 26


In [103]:
# Define empty list that will contain target variables
vowel=[]
# For each of the 1000 strings...
for i in range(len(sequences)):
  # Add target label for that string to list of labels
  vowel.append(int(contains_vowels(sequences[i])))

In [105]:
X = np.zeros((len(sequences),5,len(chars)), dtype=np.uint8)
for i, seq in enumerate(sequences):
  for t, char in enumerate(seq):
    X[i, t, char_indices[char]] = 1


Y = np.zeros((len(sequences), 1), dtype=np.uint8)
for i in range(len(sequences)):
  if (vowel[i]==1):
    Y[i,0] = 1

In [93]:
X[0,:,:]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0]], dtype=uint8)

In [94]:
## Confirm that numbers above match string below
sequences[0]

'zmjlx'

In [108]:
Y[0][0]

0

In [109]:
vowel_rnn = Sequential()
vowel_rnn.add(tfkl.LSTM(128, input_shape=(5, len(chars))))
vowel_rnn.add(tfkl.Dense(1,activation="sigmoid"))

In [110]:
vowel_rnn.compile(loss='binary_crossentropy', optimizer=tfk.optimizers.RMSprop(lr=0.01))

In [113]:
vowel_rnn.fit(X,Y, epochs=20, batch_size=1024)

Epoch 1/20
1/1 [==============================] - 0s 1ms/step - loss: 0.0987
Epoch 2/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0884
Epoch 3/20
1/1 [==============================] - 0s 1ms/step - loss: 0.0793
Epoch 4/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0709
Epoch 5/20
1/1 [==============================] - 0s 1ms/step - loss: 0.0632
Epoch 6/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0561
Epoch 7/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0496
Epoch 8/20
1/1 [==============================] - 0s 1ms/step - loss: 0.0438
Epoch 9/20
1/1 [==============================] - 0s 1ms/step - loss: 0.0386
Epoch 10/20
1/1 [==============================] - 0s 1ms/step - loss: 0.0341
Epoch 11/20
1/1 [==============================] - 0s 1ms/step - loss: 0.0302
Epoch 12/20
1/1 [==============================] - 0s 1ms/step - loss: 0.0268
Epoch 13/20
1/1 [==============================] - 0s 1ms/step - loss: 0.